package org.rhea.structure;

public enum RheaInstructionType {
    RHEA_DEF,
    RHEA_VOID,
    RHEA_PULL,
    RHEA_PUSH,
    RHEA_MOV,
    RHEA_ADD,
    RHEA_SUB,
    RHEA_MUL,
    RHEA_DIV,
    RHEA_MOD,
    RHEA_NOT,
    RHEA_OR,
    RHEA_AND,
    RHEA_XOR,
    RHEA_LSHT,
    RHEA_RSHT,
    RHEA_EQ,
    RHEA_UQ,
    RHEA_LT,
    RHEA_GT,
    RHEA_LABL,
    RHEA_JMP,
    RHEA_JMPT,
    RHEA_JMPF,
    RHEA_SYSO,
    RHEA_SYSI,
    RHEA_SYSM,
    RHEA_SYSL,
    RHEA_ARRG,
    RHEA_ARRS,
}
